### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by therewasaguy**
- Add web-component-tester as a bower dependency
- Add Test folder to thelma:seed

### CODE REVIEW

**Comment by sepans** [comment]
Great.
Can you also replace the placeholder tests in _seed-element-basic.html with the tests you created for th-data-split? (maybe it needs to be more generalized but as far as I remember there were useful for all components.)
Thanks

**Comment by therewasaguy** [comment]
Good call, I'll add our own tests to the seed. I think tests from
th-data-split could be a good starting point, but I want to put some more
thought into how to make them more generalized.

Some of the tests were dependent on the component having an outputChanged
method that fires an event. Should I also add this to the seed template
(_element-name.html) for all components? Keeping in mind that some
components won't have an output...I'm thinking that seed templates should
take into account the type of component (i.e. input, transform, visualize).

**Comment by sepans** [comment]
You are right. Lets add th-split-column tests as defaults tests, and have those which are component specific (e.g. requiring outputChanged etc.) commented out. We can later add test cases based on the category...

**Comment by therewasaguy** [comment]
just updated the PR with our own tests as a starting point

**Pull request merged**
